
import './App.css';

import MyAppBar from "./components/MyAppBar"
import Survey from './components/Survey';
var survey={"survey_id":1, 
    "survey_name":"Encuesta a profesores", 
    "survey_owner":"mvlozano", 
    "survey_description":"Encuesta de prueba 1", 
    "survey_sections":[{"section_id" : 1, 
        "section_survey_id" : 1, 
        "section_number" : 1, 
        "section_name" : "Datos Generales", 
        "section_text" : null, 
        "text_before_qestions" : false, 
        "questions" : [{"question_id":1,
            "section_id":1,
            "question_text":"Iniciales del nombre:",
            "type":2,
            "options":null,
            "question_number":1,
            "deciding":false},
            {"question_id":2,
                "section_id":1,
                "question_text":"Grado/Grupo:",
                "type":2,
                "options":null,
                "question_number":2,
                "deciding":false},
                {"question_id":3,
                    "section_id":1,
                    "question_text":"Sexo:",
                    "type":3,
                    "options":["F","M"],
                    "question_number":3,
                    "deciding":false},
                    {"question_id":4,
                        "section_id":1,
                        "question_text":"Edad",
                        "type":1,
                        "options":null,
                        "question_number":4,
                        "deciding":false},
                        {"question_id":5,
                            "section_id":1,
                            "question_text":"Municipio:",
                            "type":3,
                            "options":["SC","Camajuani","Remedios"],
                            "question_number":5,
                            "deciding":false},
                            {"question_id":6,
                                "section_id":1,
                                "question_text":"Area de la ciencia que imparte:",
                                "type":4,
                                "options":["Humanidades","Naturales","Exactas","Otras materias"],
                                "question_number":6,
                                "deciding":false}]},
                                {"section_id" : 2,
                                    "section_survey_id" : 1,
                                    "section_number" : 2,
                                    "section_name" : null,
                                    "section_text" : "En caso de que su respuesta sea afirmativa, por favor, complete el cuestionario. no hay respuestas buenas o malas. Sea sincero. Gracias por su colaboracion.",
                                    "text_before_qestions" : false,
                                    "questions" : [{"question_id":7,
                                        "section_id":2,
                                        "question_text":"Cree que sus alumnos utilizan las redes sociales?",
                                        "type":3,
                                        "options":["Si","No"],
                                        "question_number":1,
                                        "deciding":true}]},
                                        {"section_id" : 3,
                                            "section_survey_id" : 1,
                                            "section_number" : 3,
                                            "section_name" : null,
                                            "section_text" : null,
                                            "text_before_qestions" : false,
                                            "questions" : [{"question_id":8,
                                                "section_id":3,
                                                "question_text":"Cuales redes sociales crees que prefieren tus alumnos? Enumera las tres predilectas por orden de importancia:",
                                                "type":4,
                                                "options":["Facebook","Twitter","Instagram","Snapchat","Linkedin"],
                                                "question_number":1,
                                                "deciding":false},
                                                {"question_id":9,
                                                    "section_id":3,
                                                    "question_text":"¿Por qué crees que tus alumnos utilizan las redes sociales? (Puede marcar más de una opción)",
                                                    "type":4,
                                                    "options":["para hacer tareas escolares",
                                                        "para aprender",
                                                        "para conocer amigos",
                                                        "para buscar pareja",
                                                        "para leer noticias nacionales",
                                                        "para leer noticias internacionales",
                                                        "para ver videos cómicos",
                                                        "para ver películas",
                                                        "para ver series",
                                                        "para escuchar música/ver videos musicales",
                                                        "para postear/subir fotos",
                                                        "conocer lo que hacen mis amigos",
                                                        "para publicar todo lo que hago",
                                                        "para Sexting",
                                                        "para seguir influencers",
                                                        "para aprender rutinas de ejercicios/baile",
                                                        "para challengers (retos)",
                                                        "Otras"],
                                                        "question_number":2,
                                                        "deciding":false},
                                                        {"question_id":10,
                                                            "section_id":3,
                                                            "question_text":"¿Cómo crees que aprendieron tus alumnos a manejar las redes sociales? (Puede marcar más de una opción)",
                                                            "type":4,
                                                            "options":["Solos",
                                                                "Con tutoriales",
                                                                "Con amigos",
                                                                "Con sus padres/Tíos/Abuelos",
                                                                "Con sus hermanos/primos",
                                                                "Con sus parejas",
                                                                "Con sus profesores",
                                                                "Otros"],
                                                                "question_number":3,
                                                                "deciding":false}]}]}

function App() {
  return (
    <div className="App">
       <MyAppBar />
       <Survey survey={survey} />
    </div>
  );
}

export default App;
